<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="POU2" Id="{00b92a5b-c033-4c7c-87be-80a19caec9da}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU2
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU2">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>