<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="POU3" Id="{43eb077f-1080-4cfa-95d4-aac7502529e3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU3
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU3">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>