<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="POU4" Id="{2e7b3a82-d1bb-4ef3-bb60-e7bf52f565b7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU4
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU4">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>